// RDAP (Registration Data Access Protocol) Engine for Mailcoy
// Free, public ICANN standardized replacement for legacy WHOIS.

export interface RdapResult {
  domain: string;
  isRegistered: boolean;
  registrar: string | null;
  registrarId: string | null;
  nameservers: string[];
  expiresAt: string | null;
  createdAt: string | null;
  status: string[];
  raw?: any;
}

const REGISTRAR_PATTERNS: Array<{ id: string; name: string; match: RegExp; helpUrl: string; steps: string[] }> = [
  {
    id: "namecheap",
    name: "Namecheap",
    match: /namecheap|registrar-servers/i,
    helpUrl: "https://www.namecheap.com/support/knowledgebase/article.aspx/317/2237/how-do-i-add-txtspfdkimdmarc-records-for-my-domain/",
    steps: [
      "Log in to Namecheap and go to Domain List",
      "Click Manage next to your domain",
      "Click the Advanced DNS tab",
      "Add the TXT, MX, and SPF records generated by Mailcoy",
      "Click the green checkmark to save",
    ],
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    match: /cloudflare/i,
    helpUrl: "https://developers.cloudflare.com/dns/manage-dns-records/how-to/create-dns-records/",
    steps: [
      "Log in to Cloudflare Dashboard at dash.cloudflare.com",
      "Select your domain from the list",
      "Click DNS → Records",
      "Add each DNS record with Proxy set to 'DNS Only' (Grey Cloud)",
      "Save each record — takes effect instantly",
    ],
  },
  {
    id: "godaddy",
    name: "GoDaddy",
    match: /godaddy|domaincontrol/i,
    helpUrl: "https://www.godaddy.com/help/add-a-txt-record-19232",
    steps: [
      "Log in to your GoDaddy account",
      "Go to My Products → Domains → DNS",
      "Click Add in the DNS Records section",
      "Add the TXT, MX, and SPF records",
      "Click Save to apply changes",
    ],
  },
  {
    id: "hostinger",
    name: "Hostinger",
    match: /hostinger/i,
    helpUrl: "https://support.hostinger.com/en/articles/1583246",
    steps: [
      "Log in to hPanel at hpanel.hostinger.com",
      "Go to Domains → DNS / Nameservers",
      "Click Manage DNS Records → Add Record",
      "Enter the records and click Add",
    ],
  },
  {
    id: "porkbun",
    name: "Porkbun",
    match: /porkbun/i,
    helpUrl: "https://kb.porkbun.com/article/68-how-to-edit-domain-dns-records",
    steps: [
      "Log in to Porkbun and go to Domain Management",
      "Click Details next to your domain, then click Edit DNS Records",
      "Add the TXT and MX records",
      "Submit changes",
    ],
  },
  {
    id: "google",
    name: "Google Domains / Squarespace",
    match: /google|squarespace/i,
    helpUrl: "https://support.squarespace.com/hc/en-us/articles/205812348",
    steps: [
      "Log in to your Domains dashboard",
      "Navigate to DNS Settings → Custom Records",
      "Add each record and click Save",
    ],
  },
];

export async function lookupRdap(domain: string): Promise<RdapResult> {
  const cleanDomain = domain.trim().toLowerCase().replace(/^(https?:\/\/)?(www\.)?/, "").replace(/\/.*$/, "");
  
  const fallbackResult: RdapResult = {
    domain: cleanDomain,
    isRegistered: false,
    registrar: null,
    registrarId: null,
    nameservers: [],
    expiresAt: null,
    createdAt: null,
    status: [],
  };

  if (!cleanDomain || !cleanDomain.includes(".")) {
    return fallbackResult;
  }

  try {
    // Query public RDAP gateway with a 4-second timeout
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 4000);

    const res = await fetch(`https://rdap.org/domain/${encodeURIComponent(cleanDomain)}`, {
      headers: { Accept: "application/rdap+json, application/json" },
      signal: controller.signal,
    });
    clearTimeout(timeout);

    if (res.status === 404) {
      // 404 in RDAP means domain is NOT registered (Available!)
      return {
        ...fallbackResult,
        isRegistered: false,
      };
    }

    if (!res.ok) {
      return fallbackResult;
    }

    const data = await res.json();

    // Extract Registrar Name from entities
    let registrarName: string | null = null;
    if (Array.isArray(data.entities)) {
      const registrarEntity = data.entities.find((e: any) =>
        Array.isArray(e.roles) && (e.roles.includes("registrar") || e.roles.includes("sponsor"))
      );
      if (registrarEntity) {
        if (registrarEntity.vcardArray && Array.isArray(registrarEntity.vcardArray[1])) {
          const fn = registrarEntity.vcardArray[1].find((prop: any) => prop[0] === "fn");
          if (fn && fn[3]) registrarName = String(fn[3]);
        }
        if (!registrarName && registrarEntity.handle) {
          registrarName = String(registrarEntity.handle);
        }
      }
    }

    // Extract Nameservers
    const nameservers: string[] = [];
    if (Array.isArray(data.nameservers)) {
      for (const ns of data.nameservers) {
        if (ns.ldhName) nameservers.push(String(ns.ldhName).toLowerCase());
      }
    }

    // Extract Events (Created, Expires)
    let expiresAt: string | null = null;
    let createdAt: string | null = null;
    if (Array.isArray(data.events)) {
      for (const ev of data.events) {
        if (ev.eventAction === "expiration" && ev.eventDate) expiresAt = ev.eventDate;
        if (ev.eventAction === "registration" && ev.eventDate) createdAt = ev.eventDate;
      }
    }

    // Match with known registrar patterns
    let registrarId: string | null = null;
    const combinedSearch = `${registrarName || ""} ${nameservers.join(" ")}`;
    for (const pattern of REGISTRAR_PATTERNS) {
      if (pattern.match.test(combinedSearch)) {
        registrarId = pattern.id;
        if (!registrarName) registrarName = pattern.name;
        break;
      }
    }

    return {
      domain: cleanDomain,
      isRegistered: true,
      registrar: registrarName,
      registrarId,
      nameservers,
      expiresAt,
      createdAt,
      status: Array.isArray(data.status) ? data.status : [],
    };
  } catch (err) {
    console.warn(`RDAP lookup failed for ${cleanDomain}:`, err);
    return fallbackResult;
  }
}
