/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatusRouteImport } from './routes/status'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as ApiRegistrarDetectRouteImport } from './routes/api/registrar-detect'
import { Route as ApiDnsResolveRouteImport } from './routes/api/dns-resolve'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAliasSuggestionsRouteImport } from './routes/api/alias-suggestions'
import { Route as AdminStatusRouteImport } from './routes/admin/status'
import { Route as AdminPromosRouteImport } from './routes/admin/promos'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedShellRouteImport } from './routes/_authenticated/_shell'
import { Route as ApiPublicStatusRouteImport } from './routes/api/public/status'
import { Route as AuthenticatedShellTemplatesRouteImport } from './routes/_authenticated/_shell.templates'
import { Route as AuthenticatedShellSignaturesRouteImport } from './routes/_authenticated/_shell.signatures'
import { Route as AuthenticatedShellSettingsRouteImport } from './routes/_authenticated/_shell.settings'
import { Route as AuthenticatedShellLogsRouteImport } from './routes/_authenticated/_shell.logs'
import { Route as AuthenticatedShellHelpRouteImport } from './routes/_authenticated/_shell.help'
import { Route as AuthenticatedShellEmployeesRouteImport } from './routes/_authenticated/_shell.employees'
import { Route as AuthenticatedShellDomainsRouteImport } from './routes/_authenticated/_shell.domains'
import { Route as AuthenticatedShellDashboardRouteImport } from './routes/_authenticated/_shell.dashboard'
import { Route as AuthenticatedShellCatchAllRouteImport } from './routes/_authenticated/_shell.catch-all'
import { Route as AuthenticatedShellAnalyticsRouteImport } from './routes/_authenticated/_shell.analytics'
import { Route as AuthenticatedShellAliasesRouteImport } from './routes/_authenticated/_shell.aliases'
import { Route as AuthenticatedShellSettingsIndexRouteImport } from './routes/_authenticated/_shell.settings.index'
import { Route as ApiPublicWebhooksSesRouteImport } from './routes/api/public/webhooks/ses'
import { Route as ApiPublicWebhooksResendRouteImport } from './routes/api/public/webhooks/resend'
import { Route as ApiPublicWebhooksPaystackRouteImport } from './routes/api/public/webhooks/paystack'
import { Route as ApiPublicHooksVerifyDomainsRouteImport } from './routes/api/public/hooks/verify-domains'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth.google.callback'
import { Route as AuthenticatedShellSettingsWebhooksRouteImport } from './routes/_authenticated/_shell.settings.webhooks'
import { Route as AuthenticatedShellSettingsMembersRouteImport } from './routes/_authenticated/_shell.settings.members'
import { Route as AuthenticatedShellSettingsBillingRouteImport } from './routes/_authenticated/_shell.settings.billing'
import { Route as AuthenticatedShellSettingsAwsRouteImport } from './routes/_authenticated/_shell.settings.aws'
import { Route as AuthenticatedShellSettingsApiKeysRouteImport } from './routes/_authenticated/_shell.settings.api-keys'
import { Route as AuthenticatedShellEmployeesIdRouteImport } from './routes/_authenticated/_shell.employees.$id'
import { Route as AuthenticatedShellDomainsIdRouteImport } from './routes/_authenticated/_shell.domains.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegistrarDetectRoute = ApiRegistrarDetectRouteImport.update({
  id: '/api/registrar-detect',
  path: '/api/registrar-detect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDnsResolveRoute = ApiDnsResolveRouteImport.update({
  id: '/api/dns-resolve',
  path: '/api/dns-resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAliasSuggestionsRoute = ApiAliasSuggestionsRouteImport.update({
  id: '/api/alias-suggestions',
  path: '/api/alias-suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatusRoute = AdminStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPromosRoute = AdminPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShellRoute = AuthenticatedShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicStatusRoute = ApiPublicStatusRouteImport.update({
  id: '/api/public/status',
  path: '/api/public/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShellTemplatesRoute =
  AuthenticatedShellTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellSignaturesRoute =
  AuthenticatedShellSignaturesRouteImport.update({
    id: '/signatures',
    path: '/signatures',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellSettingsRoute =
  AuthenticatedShellSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellLogsRoute = AuthenticatedShellLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedShellRoute,
} as any)
const AuthenticatedShellHelpRoute = AuthenticatedShellHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedShellRoute,
} as any)
const AuthenticatedShellEmployeesRoute =
  AuthenticatedShellEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellDomainsRoute =
  AuthenticatedShellDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellDashboardRoute =
  AuthenticatedShellDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellCatchAllRoute =
  AuthenticatedShellCatchAllRouteImport.update({
    id: '/catch-all',
    path: '/catch-all',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellAnalyticsRoute =
  AuthenticatedShellAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellAliasesRoute =
  AuthenticatedShellAliasesRouteImport.update({
    id: '/aliases',
    path: '/aliases',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellSettingsIndexRoute =
  AuthenticatedShellSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedShellSettingsRoute,
  } as any)
const ApiPublicWebhooksSesRoute = ApiPublicWebhooksSesRouteImport.update({
  id: '/api/public/webhooks/ses',
  path: '/api/public/webhooks/ses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksResendRoute = ApiPublicWebhooksResendRouteImport.update({
  id: '/api/public/webhooks/resend',
  path: '/api/public/webhooks/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksPaystackRoute =
  ApiPublicWebhooksPaystackRouteImport.update({
    id: '/api/public/webhooks/paystack',
    path: '/api/public/webhooks/paystack',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksVerifyDomainsRoute =
  ApiPublicHooksVerifyDomainsRouteImport.update({
    id: '/api/public/hooks/verify-domains',
    path: '/api/public/hooks/verify-domains',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/api/auth/google/callback',
  path: '/api/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShellSettingsWebhooksRoute =
  AuthenticatedShellSettingsWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedShellSettingsRoute,
  } as any)
const AuthenticatedShellSettingsMembersRoute =
  AuthenticatedShellSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedShellSettingsRoute,
  } as any)
const AuthenticatedShellSettingsBillingRoute =
  AuthenticatedShellSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedShellSettingsRoute,
  } as any)
const AuthenticatedShellSettingsAwsRoute =
  AuthenticatedShellSettingsAwsRouteImport.update({
    id: '/aws',
    path: '/aws',
    getParentRoute: () => AuthenticatedShellSettingsRoute,
  } as any)
const AuthenticatedShellSettingsApiKeysRoute =
  AuthenticatedShellSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedShellSettingsRoute,
  } as any)
const AuthenticatedShellEmployeesIdRoute =
  AuthenticatedShellEmployeesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedShellEmployeesRoute,
  } as any)
const AuthenticatedShellDomainsIdRoute =
  AuthenticatedShellDomainsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedShellDomainsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/status': typeof AdminStatusRoute
  '/api/alias-suggestions': typeof ApiAliasSuggestionsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/dns-resolve': typeof ApiDnsResolveRoute
  '/api/registrar-detect': typeof ApiRegistrarDetectRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/aliases': typeof AuthenticatedShellAliasesRoute
  '/analytics': typeof AuthenticatedShellAnalyticsRoute
  '/catch-all': typeof AuthenticatedShellCatchAllRoute
  '/dashboard': typeof AuthenticatedShellDashboardRoute
  '/domains': typeof AuthenticatedShellDomainsRouteWithChildren
  '/employees': typeof AuthenticatedShellEmployeesRouteWithChildren
  '/help': typeof AuthenticatedShellHelpRoute
  '/logs': typeof AuthenticatedShellLogsRoute
  '/settings': typeof AuthenticatedShellSettingsRouteWithChildren
  '/signatures': typeof AuthenticatedShellSignaturesRoute
  '/templates': typeof AuthenticatedShellTemplatesRoute
  '/api/public/status': typeof ApiPublicStatusRoute
  '/domains/$id': typeof AuthenticatedShellDomainsIdRoute
  '/employees/$id': typeof AuthenticatedShellEmployeesIdRoute
  '/settings/api-keys': typeof AuthenticatedShellSettingsApiKeysRoute
  '/settings/aws': typeof AuthenticatedShellSettingsAwsRoute
  '/settings/billing': typeof AuthenticatedShellSettingsBillingRoute
  '/settings/members': typeof AuthenticatedShellSettingsMembersRoute
  '/settings/webhooks': typeof AuthenticatedShellSettingsWebhooksRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/public/hooks/verify-domains': typeof ApiPublicHooksVerifyDomainsRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
  '/api/public/webhooks/resend': typeof ApiPublicWebhooksResendRoute
  '/api/public/webhooks/ses': typeof ApiPublicWebhooksSesRoute
  '/settings/': typeof AuthenticatedShellSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/status': typeof AdminStatusRoute
  '/api/alias-suggestions': typeof ApiAliasSuggestionsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/dns-resolve': typeof ApiDnsResolveRoute
  '/api/registrar-detect': typeof ApiRegistrarDetectRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin': typeof AdminIndexRoute
  '/aliases': typeof AuthenticatedShellAliasesRoute
  '/analytics': typeof AuthenticatedShellAnalyticsRoute
  '/catch-all': typeof AuthenticatedShellCatchAllRoute
  '/dashboard': typeof AuthenticatedShellDashboardRoute
  '/domains': typeof AuthenticatedShellDomainsRouteWithChildren
  '/employees': typeof AuthenticatedShellEmployeesRouteWithChildren
  '/help': typeof AuthenticatedShellHelpRoute
  '/logs': typeof AuthenticatedShellLogsRoute
  '/signatures': typeof AuthenticatedShellSignaturesRoute
  '/templates': typeof AuthenticatedShellTemplatesRoute
  '/api/public/status': typeof ApiPublicStatusRoute
  '/domains/$id': typeof AuthenticatedShellDomainsIdRoute
  '/employees/$id': typeof AuthenticatedShellEmployeesIdRoute
  '/settings/api-keys': typeof AuthenticatedShellSettingsApiKeysRoute
  '/settings/aws': typeof AuthenticatedShellSettingsAwsRoute
  '/settings/billing': typeof AuthenticatedShellSettingsBillingRoute
  '/settings/members': typeof AuthenticatedShellSettingsMembersRoute
  '/settings/webhooks': typeof AuthenticatedShellSettingsWebhooksRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/public/hooks/verify-domains': typeof ApiPublicHooksVerifyDomainsRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
  '/api/public/webhooks/resend': typeof ApiPublicWebhooksResendRoute
  '/api/public/webhooks/ses': typeof ApiPublicWebhooksSesRoute
  '/settings': typeof AuthenticatedShellSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/_authenticated/_shell': typeof AuthenticatedShellRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/status': typeof AdminStatusRoute
  '/api/alias-suggestions': typeof ApiAliasSuggestionsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/dns-resolve': typeof ApiDnsResolveRoute
  '/api/registrar-detect': typeof ApiRegistrarDetectRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/_shell/aliases': typeof AuthenticatedShellAliasesRoute
  '/_authenticated/_shell/analytics': typeof AuthenticatedShellAnalyticsRoute
  '/_authenticated/_shell/catch-all': typeof AuthenticatedShellCatchAllRoute
  '/_authenticated/_shell/dashboard': typeof AuthenticatedShellDashboardRoute
  '/_authenticated/_shell/domains': typeof AuthenticatedShellDomainsRouteWithChildren
  '/_authenticated/_shell/employees': typeof AuthenticatedShellEmployeesRouteWithChildren
  '/_authenticated/_shell/help': typeof AuthenticatedShellHelpRoute
  '/_authenticated/_shell/logs': typeof AuthenticatedShellLogsRoute
  '/_authenticated/_shell/settings': typeof AuthenticatedShellSettingsRouteWithChildren
  '/_authenticated/_shell/signatures': typeof AuthenticatedShellSignaturesRoute
  '/_authenticated/_shell/templates': typeof AuthenticatedShellTemplatesRoute
  '/api/public/status': typeof ApiPublicStatusRoute
  '/_authenticated/_shell/domains/$id': typeof AuthenticatedShellDomainsIdRoute
  '/_authenticated/_shell/employees/$id': typeof AuthenticatedShellEmployeesIdRoute
  '/_authenticated/_shell/settings/api-keys': typeof AuthenticatedShellSettingsApiKeysRoute
  '/_authenticated/_shell/settings/aws': typeof AuthenticatedShellSettingsAwsRoute
  '/_authenticated/_shell/settings/billing': typeof AuthenticatedShellSettingsBillingRoute
  '/_authenticated/_shell/settings/members': typeof AuthenticatedShellSettingsMembersRoute
  '/_authenticated/_shell/settings/webhooks': typeof AuthenticatedShellSettingsWebhooksRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/public/hooks/verify-domains': typeof ApiPublicHooksVerifyDomainsRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
  '/api/public/webhooks/resend': typeof ApiPublicWebhooksResendRoute
  '/api/public/webhooks/ses': typeof ApiPublicWebhooksSesRoute
  '/_authenticated/_shell/settings/': typeof AuthenticatedShellSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/contact'
    | '/docs'
    | '/pricing'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/onboarding'
    | '/admin/login'
    | '/admin/organizations'
    | '/admin/promos'
    | '/admin/status'
    | '/api/alias-suggestions'
    | '/api/chat'
    | '/api/dns-resolve'
    | '/api/registrar-detect'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify'
    | '/invite/$token'
    | '/admin/'
    | '/aliases'
    | '/analytics'
    | '/catch-all'
    | '/dashboard'
    | '/domains'
    | '/employees'
    | '/help'
    | '/logs'
    | '/settings'
    | '/signatures'
    | '/templates'
    | '/api/public/status'
    | '/domains/$id'
    | '/employees/$id'
    | '/settings/api-keys'
    | '/settings/aws'
    | '/settings/billing'
    | '/settings/members'
    | '/settings/webhooks'
    | '/api/auth/google/callback'
    | '/api/public/hooks/verify-domains'
    | '/api/public/webhooks/paystack'
    | '/api/public/webhooks/resend'
    | '/api/public/webhooks/ses'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/docs'
    | '/pricing'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/onboarding'
    | '/admin/login'
    | '/admin/organizations'
    | '/admin/promos'
    | '/admin/status'
    | '/api/alias-suggestions'
    | '/api/chat'
    | '/api/dns-resolve'
    | '/api/registrar-detect'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify'
    | '/invite/$token'
    | '/admin'
    | '/aliases'
    | '/analytics'
    | '/catch-all'
    | '/dashboard'
    | '/domains'
    | '/employees'
    | '/help'
    | '/logs'
    | '/signatures'
    | '/templates'
    | '/api/public/status'
    | '/domains/$id'
    | '/employees/$id'
    | '/settings/api-keys'
    | '/settings/aws'
    | '/settings/billing'
    | '/settings/members'
    | '/settings/webhooks'
    | '/api/auth/google/callback'
    | '/api/public/hooks/verify-domains'
    | '/api/public/webhooks/paystack'
    | '/api/public/webhooks/resend'
    | '/api/public/webhooks/ses'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/about'
    | '/contact'
    | '/docs'
    | '/pricing'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/_authenticated/_shell'
    | '/_authenticated/onboarding'
    | '/admin/login'
    | '/admin/organizations'
    | '/admin/promos'
    | '/admin/status'
    | '/api/alias-suggestions'
    | '/api/chat'
    | '/api/dns-resolve'
    | '/api/registrar-detect'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify'
    | '/invite/$token'
    | '/admin/'
    | '/_authenticated/_shell/aliases'
    | '/_authenticated/_shell/analytics'
    | '/_authenticated/_shell/catch-all'
    | '/_authenticated/_shell/dashboard'
    | '/_authenticated/_shell/domains'
    | '/_authenticated/_shell/employees'
    | '/_authenticated/_shell/help'
    | '/_authenticated/_shell/logs'
    | '/_authenticated/_shell/settings'
    | '/_authenticated/_shell/signatures'
    | '/_authenticated/_shell/templates'
    | '/api/public/status'
    | '/_authenticated/_shell/domains/$id'
    | '/_authenticated/_shell/employees/$id'
    | '/_authenticated/_shell/settings/api-keys'
    | '/_authenticated/_shell/settings/aws'
    | '/_authenticated/_shell/settings/billing'
    | '/_authenticated/_shell/settings/members'
    | '/_authenticated/_shell/settings/webhooks'
    | '/api/auth/google/callback'
    | '/api/public/hooks/verify-domains'
    | '/api/public/webhooks/paystack'
    | '/api/public/webhooks/resend'
    | '/api/public/webhooks/ses'
    | '/_authenticated/_shell/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  ApiAliasSuggestionsRoute: typeof ApiAliasSuggestionsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDnsResolveRoute: typeof ApiDnsResolveRoute
  ApiRegistrarDetectRoute: typeof ApiRegistrarDetectRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiPublicStatusRoute: typeof ApiPublicStatusRoute
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
  ApiPublicHooksVerifyDomainsRoute: typeof ApiPublicHooksVerifyDomainsRoute
  ApiPublicWebhooksPaystackRoute: typeof ApiPublicWebhooksPaystackRoute
  ApiPublicWebhooksResendRoute: typeof ApiPublicWebhooksResendRoute
  ApiPublicWebhooksSesRoute: typeof ApiPublicWebhooksSesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/registrar-detect': {
      id: '/api/registrar-detect'
      path: '/api/registrar-detect'
      fullPath: '/api/registrar-detect'
      preLoaderRoute: typeof ApiRegistrarDetectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dns-resolve': {
      id: '/api/dns-resolve'
      path: '/api/dns-resolve'
      fullPath: '/api/dns-resolve'
      preLoaderRoute: typeof ApiDnsResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alias-suggestions': {
      id: '/api/alias-suggestions'
      path: '/api/alias-suggestions'
      fullPath: '/api/alias-suggestions'
      preLoaderRoute: typeof ApiAliasSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/status': {
      id: '/admin/status'
      path: '/status'
      fullPath: '/admin/status'
      preLoaderRoute: typeof AdminStatusRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/promos': {
      id: '/admin/promos'
      path: '/promos'
      fullPath: '/admin/promos'
      preLoaderRoute: typeof AdminPromosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_shell': {
      id: '/_authenticated/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedShellRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/status': {
      id: '/api/public/status'
      path: '/api/public/status'
      fullPath: '/api/public/status'
      preLoaderRoute: typeof ApiPublicStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_shell/templates': {
      id: '/_authenticated/_shell/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedShellTemplatesRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/signatures': {
      id: '/_authenticated/_shell/signatures'
      path: '/signatures'
      fullPath: '/signatures'
      preLoaderRoute: typeof AuthenticatedShellSignaturesRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/settings': {
      id: '/_authenticated/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedShellSettingsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/logs': {
      id: '/_authenticated/_shell/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedShellLogsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/help': {
      id: '/_authenticated/_shell/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedShellHelpRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/employees': {
      id: '/_authenticated/_shell/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedShellEmployeesRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/domains': {
      id: '/_authenticated/_shell/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AuthenticatedShellDomainsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/dashboard': {
      id: '/_authenticated/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedShellDashboardRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/catch-all': {
      id: '/_authenticated/_shell/catch-all'
      path: '/catch-all'
      fullPath: '/catch-all'
      preLoaderRoute: typeof AuthenticatedShellCatchAllRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/analytics': {
      id: '/_authenticated/_shell/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedShellAnalyticsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/aliases': {
      id: '/_authenticated/_shell/aliases'
      path: '/aliases'
      fullPath: '/aliases'
      preLoaderRoute: typeof AuthenticatedShellAliasesRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/settings/': {
      id: '/_authenticated/_shell/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedShellSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedShellSettingsRoute
    }
    '/api/public/webhooks/ses': {
      id: '/api/public/webhooks/ses'
      path: '/api/public/webhooks/ses'
      fullPath: '/api/public/webhooks/ses'
      preLoaderRoute: typeof ApiPublicWebhooksSesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/resend': {
      id: '/api/public/webhooks/resend'
      path: '/api/public/webhooks/resend'
      fullPath: '/api/public/webhooks/resend'
      preLoaderRoute: typeof ApiPublicWebhooksResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/paystack': {
      id: '/api/public/webhooks/paystack'
      path: '/api/public/webhooks/paystack'
      fullPath: '/api/public/webhooks/paystack'
      preLoaderRoute: typeof ApiPublicWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/verify-domains': {
      id: '/api/public/hooks/verify-domains'
      path: '/api/public/hooks/verify-domains'
      fullPath: '/api/public/hooks/verify-domains'
      preLoaderRoute: typeof ApiPublicHooksVerifyDomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/api/auth/google/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_shell/settings/webhooks': {
      id: '/_authenticated/_shell/settings/webhooks'
      path: '/webhooks'
      fullPath: '/settings/webhooks'
      preLoaderRoute: typeof AuthenticatedShellSettingsWebhooksRouteImport
      parentRoute: typeof AuthenticatedShellSettingsRoute
    }
    '/_authenticated/_shell/settings/members': {
      id: '/_authenticated/_shell/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AuthenticatedShellSettingsMembersRouteImport
      parentRoute: typeof AuthenticatedShellSettingsRoute
    }
    '/_authenticated/_shell/settings/billing': {
      id: '/_authenticated/_shell/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthenticatedShellSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedShellSettingsRoute
    }
    '/_authenticated/_shell/settings/aws': {
      id: '/_authenticated/_shell/settings/aws'
      path: '/aws'
      fullPath: '/settings/aws'
      preLoaderRoute: typeof AuthenticatedShellSettingsAwsRouteImport
      parentRoute: typeof AuthenticatedShellSettingsRoute
    }
    '/_authenticated/_shell/settings/api-keys': {
      id: '/_authenticated/_shell/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedShellSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedShellSettingsRoute
    }
    '/_authenticated/_shell/employees/$id': {
      id: '/_authenticated/_shell/employees/$id'
      path: '/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof AuthenticatedShellEmployeesIdRouteImport
      parentRoute: typeof AuthenticatedShellEmployeesRoute
    }
    '/_authenticated/_shell/domains/$id': {
      id: '/_authenticated/_shell/domains/$id'
      path: '/$id'
      fullPath: '/domains/$id'
      preLoaderRoute: typeof AuthenticatedShellDomainsIdRouteImport
      parentRoute: typeof AuthenticatedShellDomainsRoute
    }
  }
}

interface AuthenticatedShellDomainsRouteChildren {
  AuthenticatedShellDomainsIdRoute: typeof AuthenticatedShellDomainsIdRoute
}

const AuthenticatedShellDomainsRouteChildren: AuthenticatedShellDomainsRouteChildren =
  {
    AuthenticatedShellDomainsIdRoute: AuthenticatedShellDomainsIdRoute,
  }

const AuthenticatedShellDomainsRouteWithChildren =
  AuthenticatedShellDomainsRoute._addFileChildren(
    AuthenticatedShellDomainsRouteChildren,
  )

interface AuthenticatedShellEmployeesRouteChildren {
  AuthenticatedShellEmployeesIdRoute: typeof AuthenticatedShellEmployeesIdRoute
}

const AuthenticatedShellEmployeesRouteChildren: AuthenticatedShellEmployeesRouteChildren =
  {
    AuthenticatedShellEmployeesIdRoute: AuthenticatedShellEmployeesIdRoute,
  }

const AuthenticatedShellEmployeesRouteWithChildren =
  AuthenticatedShellEmployeesRoute._addFileChildren(
    AuthenticatedShellEmployeesRouteChildren,
  )

interface AuthenticatedShellSettingsRouteChildren {
  AuthenticatedShellSettingsApiKeysRoute: typeof AuthenticatedShellSettingsApiKeysRoute
  AuthenticatedShellSettingsAwsRoute: typeof AuthenticatedShellSettingsAwsRoute
  AuthenticatedShellSettingsBillingRoute: typeof AuthenticatedShellSettingsBillingRoute
  AuthenticatedShellSettingsMembersRoute: typeof AuthenticatedShellSettingsMembersRoute
  AuthenticatedShellSettingsWebhooksRoute: typeof AuthenticatedShellSettingsWebhooksRoute
  AuthenticatedShellSettingsIndexRoute: typeof AuthenticatedShellSettingsIndexRoute
}

const AuthenticatedShellSettingsRouteChildren: AuthenticatedShellSettingsRouteChildren =
  {
    AuthenticatedShellSettingsApiKeysRoute:
      AuthenticatedShellSettingsApiKeysRoute,
    AuthenticatedShellSettingsAwsRoute: AuthenticatedShellSettingsAwsRoute,
    AuthenticatedShellSettingsBillingRoute:
      AuthenticatedShellSettingsBillingRoute,
    AuthenticatedShellSettingsMembersRoute:
      AuthenticatedShellSettingsMembersRoute,
    AuthenticatedShellSettingsWebhooksRoute:
      AuthenticatedShellSettingsWebhooksRoute,
    AuthenticatedShellSettingsIndexRoute: AuthenticatedShellSettingsIndexRoute,
  }

const AuthenticatedShellSettingsRouteWithChildren =
  AuthenticatedShellSettingsRoute._addFileChildren(
    AuthenticatedShellSettingsRouteChildren,
  )

interface AuthenticatedShellRouteChildren {
  AuthenticatedShellAliasesRoute: typeof AuthenticatedShellAliasesRoute
  AuthenticatedShellAnalyticsRoute: typeof AuthenticatedShellAnalyticsRoute
  AuthenticatedShellCatchAllRoute: typeof AuthenticatedShellCatchAllRoute
  AuthenticatedShellDashboardRoute: typeof AuthenticatedShellDashboardRoute
  AuthenticatedShellDomainsRoute: typeof AuthenticatedShellDomainsRouteWithChildren
  AuthenticatedShellEmployeesRoute: typeof AuthenticatedShellEmployeesRouteWithChildren
  AuthenticatedShellHelpRoute: typeof AuthenticatedShellHelpRoute
  AuthenticatedShellLogsRoute: typeof AuthenticatedShellLogsRoute
  AuthenticatedShellSettingsRoute: typeof AuthenticatedShellSettingsRouteWithChildren
  AuthenticatedShellSignaturesRoute: typeof AuthenticatedShellSignaturesRoute
  AuthenticatedShellTemplatesRoute: typeof AuthenticatedShellTemplatesRoute
}

const AuthenticatedShellRouteChildren: AuthenticatedShellRouteChildren = {
  AuthenticatedShellAliasesRoute: AuthenticatedShellAliasesRoute,
  AuthenticatedShellAnalyticsRoute: AuthenticatedShellAnalyticsRoute,
  AuthenticatedShellCatchAllRoute: AuthenticatedShellCatchAllRoute,
  AuthenticatedShellDashboardRoute: AuthenticatedShellDashboardRoute,
  AuthenticatedShellDomainsRoute: AuthenticatedShellDomainsRouteWithChildren,
  AuthenticatedShellEmployeesRoute:
    AuthenticatedShellEmployeesRouteWithChildren,
  AuthenticatedShellHelpRoute: AuthenticatedShellHelpRoute,
  AuthenticatedShellLogsRoute: AuthenticatedShellLogsRoute,
  AuthenticatedShellSettingsRoute: AuthenticatedShellSettingsRouteWithChildren,
  AuthenticatedShellSignaturesRoute: AuthenticatedShellSignaturesRoute,
  AuthenticatedShellTemplatesRoute: AuthenticatedShellTemplatesRoute,
}

const AuthenticatedShellRouteWithChildren =
  AuthenticatedShellRoute._addFileChildren(AuthenticatedShellRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedShellRoute: typeof AuthenticatedShellRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedShellRoute: AuthenticatedShellRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminPromosRoute: typeof AdminPromosRoute
  AdminStatusRoute: typeof AdminStatusRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminPromosRoute: AdminPromosRoute,
  AdminStatusRoute: AdminStatusRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  ApiAliasSuggestionsRoute: ApiAliasSuggestionsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDnsResolveRoute: ApiDnsResolveRoute,
  ApiRegistrarDetectRoute: ApiRegistrarDetectRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiPublicStatusRoute: ApiPublicStatusRoute,
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
  ApiPublicHooksVerifyDomainsRoute: ApiPublicHooksVerifyDomainsRoute,
  ApiPublicWebhooksPaystackRoute: ApiPublicWebhooksPaystackRoute,
  ApiPublicWebhooksResendRoute: ApiPublicWebhooksResendRoute,
  ApiPublicWebhooksSesRoute: ApiPublicWebhooksSesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
